services:
  copypaste:
    image: gpigna0/copypaste:latest
    build: .
    networks:
      - copynet
    ports:
      - "${PORT}:2000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - files:/code/filedir
    develop:
      watch:
        - path: ./assets
          target: /code/assets
          action: sync
        - path: ./html
          target: /code/html
          action: sync
        - path: ./static
          target: /code/static
          action: sync
        - path: ./src
          target: /code/src
          action: rebuild

  postgres:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - copynet
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgres/data

volumes:
  db-data:
  files:

networks:
  copynet:
    name: copypaste-network
