services:
  copypaste:
    build: .
    networks:
      - copynet
    ports:
      - "2000:2000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mydb
    volumes:
      - files:/filedir
    develop:
      watch:
        - path: ./html
          target: /code/html
          action: sync
        - path: ./static
          target: /code/static
          action: sync

  postgres:
    image: postgres:16
    networks:
      - copynet
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgres/data

volumes:
  db-data:
  files:

networks:
  copynet:
    name: copypaste-network
